### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by neverroot** [etke/checksec.rs#1]
> error: attributes are not yet allowed on if expressions
>
>  --> /home/User/.cargo/registry/src/github.com-1ecc6299db9ec823/sysinfo-0.14.5/src/utils.rs:27:5
>   |
>27 |     #[allow(clippy::identity_conversion)]
>   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>
>error: aborting due to previous error
>
>error: could not compile sysinfo.
>warning: build failed, waiting for other jobs to finish...
>error: build failed

Same error above is thrown when I tried to build/install using `cargo build --release` and `cargo install checksec`

I am using cargo v1.41.0, Ubuntu 18.04 x86_64.

**Comment by etke** [comment]
Hi @RobertoBasurto,

It appears this is an issue with the sysinfo crate for rust versions <1.43.0, support for attributes on if expressions was added to the language in 1.43.0 with https://github.com/rust-lang/rust/pull/69201/.

If it is feasible try updating your rust toolchain to a version >=1.43.0.
