### ISSUE TITLE
State of project ?

### ISSUE THREAD

**Issue by AkechiShiro** [etke/checksec.rs#11]
Hi, I would like to know if this project is discontinued or just not maintained anymore ? Maybe that should be mentioned in the README.md

**Comment by etke** [comment]
Accepting PRs :smile_cat:

**Comment by AkechiShiro** [comment]
Thanks, @etke should I make a PR, updating the documentation ? 
I packaged checksec.rs for the AUR (ArchLinux User Repositories), just in order to learn a bit more about packaging a Rust package, I also ran into some troubles about tests failing (doc/documentation related tests), should I open a new issue about that ?

**Comment by etke** [comment]
@AkechiShiro, please create an issue for test failures.
